name: ${rootProject.name}
version: ${version}
main: fr.fabienhebuterne.marketplace.MarketPlace
author: fabien91
depend: [Vault]

commands:
  marketplace:
    usage: /marketplace
    description: Base command