name: Question request
description: Any question that not a feature request or bug report
labels: [ question ]

body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true