name: MarketPlace CI - Java 8 with Kotlin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install spigot nms dependencies
        run: bash ./install-dependency-in-cache.sh ${{ secrets.CI_URL }} ${{ secrets.CI_USER }} ${{ secrets.CI_PASSWORD }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle - Compile plugin with 1.12.2
        run: ./gradlew clean build -PbuildVersion=1.12.2
      - name: Build with Gradle - Compile plugin with 1.13.2
        run: ./gradlew clean build -PbuildVersion=1.13.2
      - name: Build with Gradle - Compile plugin with 1.14.4
        run: ./gradlew clean build -PbuildVersion=1.14.4
      - name: Build with Gradle - Compile plugin with 1.15.2
        run: ./gradlew clean build -PbuildVersion=1.15.2
      - name: Build with Gradle - Compile plugin with 1.16.5
        run: ./gradlew clean build -PbuildVersion=1.16.5
      - name: Set up JDK 11 for Sonar
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ''
